# Generated by Django 3.2.23 on 2024-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribe_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
