# Generated by Django 3.2.23 on 2024-02-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_userprofile_default_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='username',
            field=models.CharField(default='DefaultUsername', max_length=150),
        ),
    ]
