# Generated by Django 3.2.23 on 2024-02-16 17:46

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_newslettersubscription_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='unsubscribe_token',
            field=models.UUIDField(default=profiles.models.NewsletterSubscription.default_token, editable=False),
        ),
    ]
