# Generated by Django 3.2.23 on 2024-02-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
