# Generated by Django 3.2.23 on 2024-02-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_guest_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='guest_token',
        ),
    ]
