# Generated by Django 3.2.23 on 2024-01-26 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240125_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
